# Generated by Django 6.0.2 on 2026-02-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
